[package]
name = "skyengine-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
encoding_rs.workspace = true
flate2.workspace = true
jpeg-decoder.workspace = true
midly.workspace = true
serde.workspace = true
symphonia.workspace = true
thiserror.workspace = true
